Practica1.UI/Controllers/ReservasController.cs
using Practica1.Abstracciones.AccesoDatos.Reservas.AgregarReserva;
using Practica1.Abstracciones.AccesoDatos.Reservas.ObtenerTodasReservasAd;
using Practica1.Abstracciones.AccesoDatos.Reservas.BuscarReserva;
using Practica1.Abstracciones.AccesoDatos.Reservas.ObtenerTodasReservasAd;
using Practica1.Abstracciones.LogicaNegocio.Reservas.AgregarReservas;
using Practica1.Abstracciones.LogicaNegocio.Reservas.BuscarReserva;
using Practica1.Abstracciones.LogicaNegocio.Reservas.ObtenerReservas;
using Practica1.Abstracciones.LogicaNegocio.Reservas.ObtenerReservasDisponibles;
using Practica1.Abstracciones.LogicaNegocio.Reservas.ObternerTodasReservasLN;
using Practica1.Abstracciones.ModelosUI.Habitaciones;
using Practica1.AccesoDat.AccesoDatos.Reservas;
using Practica1.Abstracciones.ModelosUI.ReservaDetalles;
using Practica1.Abstracciones.ModelosUI.Reservas;
using Practica1.AccesoDat.AccesoDatos.Habitaciones.ListaRepuestosAD;
using Practica1.AccesoDat.AccesoDatos.Reservas.AgregarReserva;

using Practica1.AccesoDat.AccesoDatos.Reservas.BuscarReserva;

using Practica1.LogicaNegocio.Habitaciones.ListarHabitacionesLN;
using Practica1.LogicaNegocio.Habitaciones.ObtenerHabitacionesDisponiblesLN;
using Practica1.LogicaNegocio.Reservas.AgregarReservaLN;
using Practica1.LogicaNegocio.Reservas.BuscarReservaLN;
using Practica1.LogicaNegocio.Reservas.ObtenerReserva;
using Practica1.LogicaNegocio.Reservas.ObtenerTodasReservasLN;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
namespace Practica1.UI.Controllers
{
    public class ReservasController : Controller
    {
        private readonly IObtenerReservaLN _ObtenerReservaLN;
        private readonly IObtenerHabitacionesDisponiblesLN _ObtenerHabitacionesLN;
        private readonly IBuscarReservaLN _BuscarReservaLN;
        private readonly IAgregarReservaLN _AgregarReservaLN;
        private readonly IBuscarReservaLN _buscarReservaLN;
        private readonly IObtenerTodasReservasLN _reservasLN;

        public ReservasController()
        {
            ObtenerListaHabitaciones habitacionesAD = new ObtenerListaHabitaciones();
            _ObtenerReservaLN = new ObtenerReservasLN();
            IBuscarReservaAD buscarReservaAD = new BuscarReservaAD();
            _BuscarReservaLN = new BuscarReservaLN(buscarReservaAD);
            _ObtenerHabitacionesLN = new ObtenerHabitacionesDisponiblesLN(habitacionesAD);
            IAgregarReservaAD agregarReservaAD = new AgregarReservaAD();
            _AgregarReservaLN = new AgregarReservaLN(agregarReservaAD, habitacionesAD);
            _buscarReservaLN = new BuscarReservaLN(new BuscarReservaAD());
            IObtenerTodasReservasAd reservasAd = new ObtenerTodasReservasAD();
            _reservasLN = new ObtenerTodasReservasLN(reservasAd);
        }


        // GET: Reservas
        public ActionResult Index()
        {
            return View();
        }

        // GET: Reservas/ListaReservasHabitacion/5
        public ActionResult ListaReservasHabitacion(int? idHabitacion)
        {
            List<ReservaDetalleDTO> lista;

            if (idHabitacion.HasValue)
            {
                lista = _reservasLN.ObtenerPorIdHabitacion(idHabitacion.Value);
            }
            else
            {
                lista = _reservasLN.ObtenerTodas();
            }

            return View(lista);
        }
    

        // GET: Reservas/Listar
        [HttpGet]
        public ActionResult Listar()
        {
            List<HabitacionDTO> habitaciones = _ObtenerHabitacionesLN.Obtener();
            return View(habitaciones);
        }




        [HttpGet]
        // Haz el 'id' opcional
        public ActionResult ListaHabitacionesParcial(ReservacionesDTO Reservas)
        {
           
          List<ReservacionesDTO> habitaciones = _ObtenerReservaLN.Obtener();
            return PartialView("ListaHabitacionesParcial", habitaciones);
        }







        // POST: Reservas/BuscarReserva
        [HttpPost]
        public ActionResult BuscarReserva(int idReservacion)
        {
            ReservaDetalleDTO reserva = _BuscarReservaLN.BuscarPorIdHabitacion(idReservacion);
            return RedirectToAction("Detalles", new { idReservacion = idReservacion });
        }

        // GET: Reservas/Detalles/5
        public ActionResult Detalles(int id)
        {
            ReservaDetalleDTO reservaDetalle = _buscarReservaLN.BuscarPorIdHabitacion(id);

            if (reservaDetalle == null)
            {
               
                return RedirectToAction("ListaReservasHabitacion");
            }

            return View(reservaDetalle);
        }



        // POST: Reservas/Reservar
        [HttpGet]
        public ActionResult Reservar()
        {
            ReservacionesDTO modelo = new ReservacionesDTO();
            List<HabitacionDTO> habitaciones = _ObtenerHabitacionesLN.Obtener();
            ViewBag.Habitaciones = new SelectList(habitaciones, "ID", "Nombre");
            return View(modelo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Reservar(ReservacionesDTO reservaNueva)
        {
            if (!ModelState.IsValid)
            {
                List<HabitacionDTO> habitaciones = _ObtenerHabitacionesLN.Obtener();
                ViewBag.Habitaciones = new SelectList(habitaciones, "ID", "Nombre");
                return View(reservaNueva);
            }
                        try
            {
                int idReservaGenerada = await _AgregarReservaLN.Ejecutar(reservaNueva);
                              ;

                return RedirectToAction("ListaReservasHabitacion", new { idHabitacion = reservaNueva.IdHabitacion });
            }
            catch (Exception ex)
            {
                List<HabitacionDTO> habitaciones = _ObtenerHabitacionesLN.Obtener();
                ViewBag.Habitaciones = new SelectList(habitaciones, "ID", "Nombre");
                return View(reservaNueva);
            }
        }
    }
}

Practica1.UI/Views/Reservas/Detalles.cshtml
@model Practica1.Abstracciones.ModelosUI.ReservaDetalles.ReservaDetalleDTO

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>ReservaDetalleDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NombreDeLaPersona)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreDeLaPersona)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Identificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Identificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MontoTotal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaInicioReserva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaInicioReserva)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaFinReserva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaFinReserva)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDeRegistro)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IdHabitacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IdHabitacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CodigoDeHabitacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CodigoDeHabitacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NombreDeHabitacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NombreDeHabitacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CantidadDeHuespedesPermitidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CantidadDeHuespedesPermitidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDeHabitacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDeHabitacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoDeHabitacionTexto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoDeHabitacionTexto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostoDeReserva)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostoDeReserva)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Practica1.UI/Views/Reservas/ListaHabitacionesParcial.cshtml
@model IEnumerable<Practica1.Abstracciones.ModelosUI.Reservas.ReservacionesDTO>
<div class="table-responsive">  
<table class="table table-responsive">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NombreDeLaPersona)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Identificacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Correo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontoTotal)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaInicioReserva)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaFinReserva)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaDeRegistro)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IdHabitacion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NombreDeLaPersona)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Identificacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Correo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MontoTotal)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaInicioReserva)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaFinReserva)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaDeRegistro)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IdHabitacion)
        </td>
      
    </tr>
}

</table>

Practica1.UI/Views/Reservas/ListaReservasHabitacion.cshtml
@model IEnumerable<Practica1.Abstracciones.ModelosUI.ReservaDetalles.ReservaDetalleDTO>
@{
    ViewBag.Title = "ListaReservasHabitacion";
}
<h2>ListaReservasHabitacion</h2>
<p>
    @Html.ActionLink("Create New", "Reservar")
    <button type="button" class="btn btn-primary" id="AbrirModal">
        Ver Reservas
    </button>
    <input id="Nombres" class="form-control">

</p>
<table class="table" id="myTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreDeLaPersona)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Identificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefono)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Correo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Direccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MontoTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaInicioReserva)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaFinReserva)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDeRegistro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdHabitacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreDeLaPersona)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Identificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Telefono)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Correo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Direccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MontoTotal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaInicioReserva)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaFinReserva)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDeRegistro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdHabitacion)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
    </tbody>
</table>




<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="Guardar">Save changes </button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/Reservas/ListarResrvas.js"></script>
}

Practica1.UI/Views/Reservas/Listar.cshtml
@model IEnumerable<Practica1.Abstracciones.ModelosUI.Habitaciones.HabitacionDTO>

@{
    ViewBag.Title = "Lista_de_Habitaciones";
}

<h2>Lista_de_Habitaciones</h2>

<p>
    @Html.ActionLink("Create New", "Crear_Habitacion")
</p>

@if (TempData["Mensaje"] != null)
{
    <div class="alert alert-warning">
        @TempData["Mensaje"]
    </div>
}

<hr />

@if (Model != null && Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Codigo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Ubicacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadHuespedesAdmitidos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadCamas)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CantidadBanos)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ResponsableLimpieza)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CostoLimpieza)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CostoReserva)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TipoHabitacion)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Estado)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaRegistro)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FechaModificacion)
                </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>

            <li>@Html.ActionLink("Nueva Reserva.", "ListaReservasHabitacion", "Reservas", new { area = "" }, new { @class = "nav-link" })</li>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Codigo)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Ubicacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadHuespedesAdmitidos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadCamas)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CantidadBanos)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ResponsableLimpieza)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CostoLimpieza)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CostoReserva)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TipoHabitacion)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Estado)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaRegistro)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FechaModificacion)
                    </td>
                    <td>
                        @Html.ActionLink("Editar", "Editar_Habitacion", new { id = item.ID }) |
                        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/Scripts/Reservas/ListarResrvas.js"></script>
}

Practica1.UI/Views/Reservas/Reservar.cshtml
@model Practica1.Abstracciones.ModelosUI.Reservas.ReservacionesDTO

@using (Html.BeginForm("Reservar", "Reservas", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.LabelFor(m => m.NombreDeLaPersona)
        @Html.TextBoxFor(m => m.NombreDeLaPersona)
        @Html.ValidationMessageFor(m => m.NombreDeLaPersona)
    </div>

    <div>
        @Html.LabelFor(m => m.Identificacion)
        @Html.TextBoxFor(m => m.Identificacion)
        @Html.ValidationMessageFor(m => m.Identificacion)
    </div>

    <div>
        @Html.LabelFor(m => m.Telefono)
        @Html.TextBoxFor(m => m.Telefono)
        @Html.ValidationMessageFor(m => m.Telefono)
    </div>

    <div>
        @Html.LabelFor(m => m.Correo)
        @Html.TextBoxFor(m => m.Correo)
        @Html.ValidationMessageFor(m => m.Correo)
    </div>

    <div>
        @Html.LabelFor(m => m.FechaNacimiento)
        @Html.TextBoxFor(m => m.FechaNacimiento, "{0:yyyy-MM-dd}", new { type = "date" })
        @Html.ValidationMessageFor(m => m.FechaNacimiento)
    </div>

    <div>
        @Html.LabelFor(m => m.Direccion)
        @Html.TextBoxFor(m => m.Direccion)
        @Html.ValidationMessageFor(m => m.Direccion)
    </div>

    <div>
        @Html.LabelFor(m => m.FechaNacimiento)
        @Html.TextBoxFor(m => m.FechaNacimiento, new
        {
            type = "date",
            @class = "form-control",
            required = "required",
            min = "1900-01-01",  // Fecha mínima
            max = DateTime.Now.ToString("yyyy-MM-dd")  // Máximo hoy
        })
        @Html.ValidationMessageFor(m => m.FechaNacimiento)
    </div>

    <div>
        @Html.LabelFor(m => m.FechaInicioReserva)
        @Html.TextBoxFor(m => m.FechaInicioReserva, new { type = "date", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FechaInicioReserva)
    </div>

    <div>
        @Html.LabelFor(m => m.FechaFinReserva)
        @Html.TextBoxFor(m => m.FechaFinReserva, new { type = "date", @class = "form-control" })
        @Html.ValidationMessageFor(m => m.FechaFinReserva)
    </div>

    <div>
        @Html.LabelFor(m => m.IdHabitacion, "Habitación")
        @Html.DropDownListFor(m => m.IdHabitacion,
            (SelectList)ViewBag.Habitaciones,
            "-- Seleccione una habitación --",
            new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.IdHabitacion)
    </div>

    <button type="submit">Agregar Reserva</button>
}